### ISSUE TITLE
TypeError: Cannot read property 'getAttribute' of null when testing with jest

### ISSUE THREAD

**Issue by BenSwennen** [andreypopp/react-textarea-autosize#120]
I have a UserNote component that uses a TextArea from react-textarea-autosize and it works when previewing it in browser. However when I test the UserNote component, I get following error:

``` javascript
    TypeError: Cannot read property 'getAttribute' of null

      at calculateNodeStyling (node_modules/react-textarea-autosize/lib/calculateNodeHeight.js:82:21)
      at calculateNodeHeight (node_modules/react-textarea-autosize/lib/calculateNodeHeight.js:31:31)
      at TextareaAutosize._resizeComponent (node_modules/react-textarea-autosize/lib/TextareaAutosize.js:146:55)
      at TextareaAutosize.componentDidMount (node_modules/react-textarea-autosize/lib/TextareaAutosize.js:89:12)
      at node_modules/react/lib/ReactCompositeComponent.js:264:25
      at measureLifeCyclePerf (node_modules/react/lib/ReactCompositeComponent.js:74:12)
      at node_modules/react/lib/ReactCompositeComponent.js:263:11
      at CallbackQueue.notifyAll (node_modules/react/lib/CallbackQueue.js:67:22)
      at ReactTestReconcileTransaction.close (node_modules/react/lib/ReactTestReconcileTransaction.js:37:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react/lib/Transaction.js:204:25)
      at ReactTestReconcileTransaction.perform (node_modules/react/lib/Transaction.js:151:16)
      at batchedMountComponentIntoNode (node_modules/react/lib/ReactTestMount.js:63:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react/lib/Transaction.js:138:20)
      at Object.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
      at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:98:20)
      at Object.render (node_modules/react/lib/ReactTestMount.js:120:18)
      at Object.<anonymous> (src/components/Notes/__tests__/UserNote.test.js:45:75)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

Is there something I am doing wrong?

**Comment by rovansteen** [comment]
That's because it assumes a browser context where it can calculate the node height. With something like react-test-renderer the property `getAttribute` is not available. A workaround is to use Enzyme's mount which does simulate a browser context. Then you can use something like [enzyme-to-json](https://github.com/adriantoine/enzyme-to-json) to do snapshot testing with Jest.

**Comment by khankuan** [comment]
I've added a safety check to `_resizeComponent` so that it is only called when root dom node is available. That would be very helpful for tests that breaks from snapshot testing.

**Comment by Andarist** [comment]
Safety checked released, so Im closing this.
